spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pismo
    username: root
    password: abcd1234
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
  jackson:
    property-naming-strategy: SNAKE_CASE